version: "3.9"

services:
  redis:
    tty: true
    image: battleships-redis:latest
    restart: always
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - cache:/data

  backend:
    container_name: backend
    image: battleships-backend
    depends_on:
      - redis
    environment:
      REDIS_PORT: 6379
      REDIS_HOST: redis
      IO_PORT: 8000
      DEBUG: debug
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 3000:3000
      - 8000:8000

  frontend:
    container_name: frontend
    image: battleships-frontend
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        REACT_APP_IO_PORT: 8000
    ports:
      - 8080:80

volumes:
  cache:
    driver: local
