version: "3.9"

services:
  redis:
    tty: true
    image: redis:latest
    restart: always
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - cache:/data

  api:
    container_name: api
    image: ghcr.io/vvcodeweb/battleships-api:latest
    pull_policy: never
    depends_on:
      - redis
    environment:
      REDIS_PORT: 6379
      REDIS_HOST: redis
      DEBUG: debug
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 3000:3000

  ui:
    container_name: ui
    image: ghcr.io/vvcodeweb/battleships-ui:latest
    pull_policy: never
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - 8080:80

volumes:
  cache:
    driver: local
